# Production
FROM maven:3.5.2-jdk-8-alpine AS MAVEN_TOOL_CHAIN
COPY pom.xml /tmp/
COPY db-configs.properties /tmp/
COPY src /tmp/src/
WORKDIR /tmp/
RUN mvn package

FROM openjdk:8-jdk-alpine
EXPOSE 8080
COPY --from=MAVEN_TOOL_CHAIN /tmp/db-configs.properties db-configs.properties
COPY --from=MAVEN_TOOL_CHAIN /tmp/target/dash-browser-automation-0.1.0.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]