version: '3'
services:
  dash-browser-automation:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: dash-browser-automation:0.1.0
    restart: always
    labels:
      - "traefik.docker.network=dash-net"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:dash-browser-automation.speedegree.tk"
      - "traefik.port=8080"
      - "traefik.backend=dash-browser-automation"
    ports:
      - "8080:8080"
    networks:
      - dash-net
    depends_on:
      - chrome
    
  chrome:
    image: "selenium/standalone-chrome"
    restart: always
    expose:
      - "4444"
    networks:
      - dash-net

networks:
  dash-net:
    external: true

